version: '3.8'

services:
  bot:
    build: .  # Собираем контейнер из Dockerfile в текущей директории
    container_name: selenium-bot  # Имя контейнера
    restart: unless-stopped  # Автоматический перезапуск контейнера, если он остановится
    volumes:
      - .:/app  # Монтирование текущей директории в контейнер (чтобы изменения в коде сразу применялись)