version: '3.8'

services:
  bot:
    build: .
    container_name: selenium-bot
    restart: unless-stopped
    volumes:
      - .:/appdir
      - db_data:/db
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - selenium
      - db
    

  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium-server
    ports:
      - "4444:4444"
    shm_size: "2g"
    volumes:
      - ./Parser/extension:/extension  # Монтируем папку с расширением
    environment:
      - TZ=Europe/Moscow

  db:
    image: alpine
    container_name: sqlite-db
    volumes:
      - db_data:/db
    command: ["sh", "-c", "tail -f /dev/null"]
    restart: unless-stopped

volumes:
  db_data:
